name: wishlist
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  google_fonts: ^2.1.0

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - lib/assets/images/
    - lib/assets/fonts/
  fonts:
    - family: Dosis
      fonts:
        - asset: lib/assets/fonts/Dosis-VariableFont_wght.ttf
    - family: HindMadurai
      fonts:
        - asset: lib/assets/fonts/HindMadurai-Medium.ttf
    - family: IstokWeb
      fonts:
        - asset: lib/assets/fonts/IstokWeb-Regular.ttf
#    - family: Karla
#      fonts:
#        - asset: lib/assets/fonts/Karla-VariableFont_wght.ttf
    - family: Murechob
      fonts:
        - asset: lib/assets/fonts/Murecho-Bold.ttf
    - family: SonsieOn
      fonts:
        - asset: lib/assets/fonts/SonsieOne-Regular.ttf
#    - family: ZenKakuGothicNew
#      fonts:
#        - asset: lib/assets/fonts/ZenKakuGothicNew-Medium.ttf
    - family: ZillaSlabHighlight
      fonts:
        - asset: lib/assets/fonts/ZillaSlabHighlight-Regular.ttf
    - family: Zilla
      fonts:
        - asset: lib/assets/fonts/ZillaSlabHighlight-Bold.ttf
    - family: Monoton
      fonts:
        - asset: lib/assets/fonts/Monoton-Regular.ttf
    - family: Caveat
      fonts:
        - asset: lib/assets/fonts/Caveat-Medium.ttf
    - family: Comfortaa
      fonts:
        - asset: lib/assets/fonts/Comfortaa-Medium.ttf
    - family: MPLUSRound
      fonts:
        - asset: lib/assets/fonts/MPLUSRounded1c-Medium.ttf
    - family: ZenMaruGothic
      fonts:
        - asset: lib/assets/fonts/ZenMaruGothic-Medium.ttf